### ISSUE TITLE
Community: Gitter Channel

### ISSUE THREAD

**Issue by cgmcintyr** [cholcombe973/rusix#14]
I found out about this project through [this reddit post](https://www.reddit.com/r/rust/comments/98d3zk/call_for_help_building_a_distributed_filesystem/) and I imagine at least a few others have stumbled across this project the same way.

Having a Gitter channel someone can say hi in is less scary than opening a GitHub issue :)

**Comment by cholcombe973** [comment]
Yeah good point.  I've never made a channel before.  Would you want to create one and then invite me?  We were chatting awhile on irc if that interests you as well.

**Comment by cgmcintyr** [comment]
Unfortunately I would need maintainer access to this repository, or if you were to create a rusix organisation and I was a member.

Gitter supports OAuth Github login, so it should only be a couple of clicks to get started: https://gitter.im/

**Comment by cgmcintyr** [comment]
A button can be added to the README using 
```
[![Join the chat at https://gitter.im/publiclab/publiclab](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/ROOMNAMEHERE)
```

Which would look like this:
[![Join the chat at https://gitter.im/publiclab/publiclab](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/ROOMNAMEHERE)

**Comment by cholcombe973** [comment]
So for whatever reason this didn't work on my laptop last night but worked this morning on my desktop: https://gitter.im/rust-rusix/community
