### ISSUE TITLE
Decide on a license

### ISSUE THREAD

**Issue by cholcombe973** [cholcombe973/rusix#7]
Gluster and Ceph are both LGPL.  What should this project be?

**Comment by garypen** [comment]
I don't think the LGPL is a good choice. It's a product of its time and doesn't make much sense nowadays: even GNU org think it should be avoided: https://www.gnu.org/licenses/why-not-lgpl.en.html.

I personally favour Apache 2.0. I'd also be happy with MIT or MPL. I could be convinced to consider full GPL (I think the most current incarnation is known as AGPL), but I think that any of my first three suggestions would be "better" (in terms of maximising user options and re-use).

**Comment by cholcombe973** [comment]
@garypen oh yeah the apache license on the Cargo.toml.  So from what I've heard from lawyers on previous repos that doesn't mean anything unless the license file is actually on the repo so just ignore that haha.  Sounds like we're looking at either AGPL or Apache 2.0.

**Comment by jcgruenhage** [comment]
I'd prefer AGPL, but that might scare off some potential contributors, especially from corporate environments.

**Comment by jcgruenhage** [comment]
Going for Apache/MIT would help with reusing code for other rust projects, but would help proprietors. When I said that that it might scare off contributors that was meant as a minor concern, not that I am against the AGPL. I still very much prefer it, and Linux proves that GPL and corporate interests can be brought together.

**Comment by garypen** [comment]
Ok. I agree about GPL working for some interests, but I think it can cause issues for some developers and potentially for some users. We might as well avoid such issues if we don't have strong feelings that mean we favour AGPL really strongly.

Ok. I don't think there's much more to be gained from further debating this decision. Let's have a vote. I vote for same license as Rust: i.e. dual license APL 2.0/MIT.

**Comment by cholcombe973** [comment]
I personally like Apache 2.0.  I looked up [Apache 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) and [AGPL](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)) and it looks they're very similar but divulge on sublicensing vs holding liable.  I think APL 2.0/MIT is fine for now.  It sounds like we're all in agreement there.  If anyone feels really strongly about this feel free to reopen and we'll discuss more :)
