### ISSUE TITLE
build requires linux OS and various packages which aren't present in a typical default install

### ISSUE THREAD

**Issue by garypen** [cholcombe973/rusix#9]
When I built rusix I had to install the following packages on my vanilla centos workstation:

sudo yum install libudev-devel openssl-devel zeromq-devel capnproto-devel capnproto

Should we call this out in our documentation and is this a reasonably complete list?

Also: should we document that only linux OS systems are supported for development and execution due to the dependency on libudev?

Justification: ergonomics.

**Comment by cholcombe973** [comment]
Yeah I think that's a pretty comprehensive list for the moment.
Unfortunately I think we're stuck Linux only at the moment.  I think it's
fair to point out in the docs

**Comment by garypen** [comment]
Ok. I've updated Contributing.md with this information.

**Comment by cholcombe973** [comment]
Awesome thanks!
